# 基础镜像
FROM redis
# author
MAINTAINER thinglinks

# 挂载目录
VOLUME /www/wwwroot/thinglinks/redis
# 创建目录
RUN mkdir -p /www/wwwroot/thinglinks/redis
# 指定路径
WORKDIR /www/wwwroot/thinglinks/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /www/wwwroot/thinglinks/redis/redis.conf
