# 基础镜像
FROM nginx:1.22
# author
MAINTAINER thinglinks

# 挂载目录
VOLUME /www/wwwroot/thinglinks/thinglinks-ui
# 创建目录
RUN mkdir -p /www/wwwroot/thinglinks/thinglinks-ui
# 指定路径
WORKDIR /www/wwwroot/thinglinks/thinglinks-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /www/wwwroot/thinglinks/thinglinks-ui
