/**
 * 后端服务请求 前缀
 */
export enum ServicePrefixEnum {
  // 系统服务
  TENANT = '/system',
  // 文件服务
  FILE = '/base',
  // 消息服务
  MSG = '/base',
  // 网关
  GATEWAY = '/gateway',
  // 认证服务
  OAUTH = '/oauth',
  // 基础服务
  BASE = '/base',
  // 系统服务
  SYSTEM = '/system',
  // 代码生成器服务
  GENERATOR = '/generator',
  // 工作流
  ACTIVITI = '/activiti',
  // 物联网业务系统-设备集成link
  LINK = '/link',
  // 物联网业务系统-规则引擎
  RULE = '/rule',
  // 物联网业务系统-消息治理(协议总线)
  MQS = '/mqs',
  // 流媒体业务系统
  VIDEO = '/video',
  // 开放平台服务
  SOPADMIN = '/sopadmin',
}

/**
 * 操作列 类型
 */
export enum ActionEnum {
  // 新增
  ADD = 'add',
  // 编辑
  EDIT = 'edit',
  // 复制
  COPY = 'copy',
  // 删除
  DELETE = 'delete',
  // 详情
  VIEW = 'view',
}

export const VALIDATE_API = {
  [ActionEnum.ADD]: 'Save',
  [ActionEnum.EDIT]: 'Update',
  [ActionEnum.COPY]: 'Save',
};

/**
 * 文件的业务 类型
 */
export enum FileBizTypeEnum {
  // 默认库 租户logo
  DEF_TENANT_LOGO = 'DEF__TENANT__LOGO',
  // 默认库 应用logo
  DEF_APPLICATION_LOGO = 'DEF__APPLICATION__LOGO',
  // 基础库 用户头像
  BASE_USER_AVATAR = 'DEF__USER__AVATAR',
  // 基础库 文件中心
  BASE_FILE = 'BASE__FILE',
  // 扩展库 消息内容附件
  EXTEND_MSG_CONTENT = 'EXTEND__MSG__CONTENT',
  // 基础库 OTA资源 升级包位置
  BASE_LINK_OTA_PACK = 'BASE_LINK_OTA_PACK',
  // 基础库 产品管理 icon
  BASE_LINK_PRODUCT_ICON = 'BASE_LINK_PRODUCT_ICON',
  // 基础库 插件信息 文件在服务器上的唯一标识
  BASE_LINK_PLUGIN_INFO_FILEID = 'BASE_LINK_PLUGIN_INFO_FILEID',
}

/**
 * 文件的 桶 （需要提前跟后端约定，并让后端配置到OSS中）
 */
export enum FileBucketEnum {
  // 需要自行在华为云或minio等第三方对象存储提前创建 公开读写的桶
  public = 'tt-public',
}

export enum DictEnum {
  // 全局
  AREA_LEVEL = 'GLOBAL_AREA_LEVEL',
  NATION = 'GLOBAL_NATION',
  SEX = 'Sex',
  EDUCATION = 'GLOBAL_EDUCATION',
  TENANT_AMAP__AAPPLICATION_JS_API_KEY = 'TENANT_AMAP__AAPPLICATION_JS_API_KEY',
  TENANT_AMAP__AAPPLICATION_WEB_SERVICES_API_KEY = 'TENANT_AMAP__AAPPLICATION_WEB_SERVICES_API_KEY',

  // 注册来源
  SOP_API_INFO_REG_SOURCE = 'SOP_API_INFO_REG_SOURCE',
  AuditStatusEnum = 'AuditStatusEnum',
  DataScopeEnum = 'DataScopeEnum',
  DefTenantStatusEnum = 'DefTenantStatusEnum',
  FileStorageType = 'FileStorageType',
  MsgInterfaceLoggingStatusEnum = 'MsgInterfaceLoggingStatusEnum',
  VxeComponentEnum = 'VxeComponentEnum',
  ComponentEnum = 'ComponentEnum',
  FileOverrideStrategyEnum = 'FileOverrideStrategyEnum',
  GenTypeEnum = 'GenTypeEnum',
  NoticeRemindModeEnum = 'NoticeRemindModeEnum',
  SqlConditionEnum = 'SqlConditionEnum',
  DefTenantRegisterTypeEnum = 'DefTenantRegisterTypeEnum',
  FileType = 'FileType',
  HttpMethod = 'HttpMethod',
  LogType = 'LogType',
  SuperClassEnum = 'SuperClassEnum',
  TemplateEnum = 'TemplateEnum',
  ClientTypeEnum = 'ClientTypeEnum',
  GrantType = 'GrantType',
  MsgTemplateCodeEnum = 'MsgTemplateCodeEnum',
  OrgTypeEnum = 'OrgTypeEnum',
  ProductType = 'ProductType',
  TaskStatus = 'TaskStatus',
  DateType = 'DateType',
  DefGenTestSimpleType2Enum = 'DefGenTestSimpleType2Enum',
  InterfaceExecModeEnum = 'InterfaceExecModeEnum',
  RoleCategoryEnum = 'RoleCategoryEnum',
  UserStatusEnum = 'UserStatusEnum',
  DataTypeEnum = 'DataTypeEnum',
  DefGenTestTreeType2Enum = 'DefGenTestTreeType2Enum',
  LoginStatusEnum = 'LoginStatusEnum',
  PopupTypeEnum = 'PopupTypeEnum',
  TplEnum = 'TplEnum',
  DictClassifyEnum = 'DictClassifyEnum',
  EntitySuperClassEnum = 'EntitySuperClassEnum',
  NotificationChannelType = 'NotificationChannelType',
  ResourceTypeEnum = 'ResourceTypeEnum',
  SoyComponentEnum = 'SoyComponentEnum',
  TenantConnectTypeEnum = 'TenantConnectTypeEnum',
  ActiveStatusEnum = 'ActiveStatusEnum',
  MsgTemplateTypeEnum = 'MsgTemplateTypeEnum',
  ResourceOpenWithEnum = 'ResourceOpenWithEnum',
  Sex = 'Sex',
  SourceType = 'SourceType',
  SendStatus = 'SendStatus',
  ProviderType = 'ProviderType',
  MsgBizType = 'MsgBizType',
  MsgType = 'MsgType',
  ApplicationAppTypeEnum = 'ApplicationAppTypeEnum',
  TenantStatusEnum = 'TenantStatusEnum',
  TenantTypeEnum = 'TenantTypeEnum',
  AuthorizeType = 'AuthorizeType',
  DataScopeType = 'DataScopeType',

  // base
  POSITION_STATUS = 'BASE_POSITION_STATUS',
  EchoDictType_Base_NOTICE_TARGET = 'NOTICE_TARGET',
  // tenant
  RESOURCE_TRANSITION_NAME = 'TENANT_RESOURCE_TRANSITION_NAME',
  DICT_TYPE = 'TENANT_DICT_TYPE',
  PARAMETER_TYPE = 'TENANT_PARAMETER_TYPE',
  APPLICATION_TYPE = 'TENANT_APPLICATION_TYPE',
  CLIENT_TYPE = 'TENANT_CLIENT_TYPE',
  AREA_SOURCE = 'TENANT_AREA_SOURCE',
  DictionaryType_Global_EDUCATION = 'GLOBAL_EDUCATION',
  DictionaryType_Global_DATA_TYPE = 'DATA_TYPE',

  TENANT_LOGIN_STATUS = 'TENANT_LOGIN_STATUS',
  DICT_I18N = 'I18N_JSON',
  NotifyStatusEnum = 'NotifyStatusEnum',

  // link
  LINK_DEVICE_STATUS = 'LINK_DEVICE_STATUS',
  LINK_DEVICE_CONNECT_STATUS = 'LINK_DEVICE_CONNECT_STATUS',
  LINK_PRODUCT_PROTOCOL_TYPE = 'LINK_PRODUCT_PROTOCOL_TYPE',
  LINK_DEVICE_NODE_TYPE = 'LINK_DEVICE_NODE_TYPE',
  LINK_DEVICE_AUTH_MODE = 'LINK_DEVICE_AUTH_MODE',
  LINK_DEVICE_ENCRYPT_METHOD = 'LINK_DEVICE_ENCRYPT_METHOD',
  LINK_DEVICE_CONNECTOR = 'LINK_DEVICE_CONNECTOR',
  CARD_APPLICATION_SCENARIO = 'CARD_APPLICATION_SCENARIO',
  LINK_PRODUCT_SERVICE_TYPE = 'LINK_PRODUCT_SERVICE_TYPE',
  ACCESS_MODE = 'ACCESS_MODE',
  LINK_PRODUCT_SERVICE_REQUIRED = 'LINK_PRODUCT_SERVICE_REQUIRED',
  LINK_PRODUCT_STATUS = 'LINK_PRODUCT_STATUS',
  LINK_PRODUCT_DATA_FORMAT = 'LINK_PRODUCT_DATA_FORMAT',
  LINK_PRODUCT_SERVICE_COMMAND_DATA_TYPE = 'LINK_PRODUCT_SERVICE_COMMAND_DATA_TYPE',
  LINK_DEVICE_ACTION_TYPE = 'LINK_DEVICE_ACTION_TYPE',
  LINK_DEVICE_COMMAND_TYPE = 'LINK_DEVICE_COMMAND_TYPE',
  LINK_PRODUCT_TYPE = 'LINK_PRODUCT_TYPE',
  LINK_PRODUCT_SERVICE_PROPERTY_DATA_TYPE = 'LINK_PRODUCT_SERVICE_PROPERTY_DATA_TYPE',
  LINK_APPLICATION_SCENARIO = 'LINK_APPLICATION_SCENARIO',
  LINK_DEVICE_ACTION_STATUS = 'LINK_DEVICE_ACTION_STATUS',
  LINK_DEVICE_COMMAND_STATUS = 'LINK_DEVICE_COMMAND_STATUS',
  LINK_ACL_RULE_LEVEL = 'LINK_ACL_RULE_LEVEL',
  LINK_ACL_RULE_ACTION_TYPE = 'LINK_ACL_RULE_ACTION_TYPE',
  // CA 证书状态/算法/审计类型 (cacert_seed.sql 落地)
  LINK_CA_CERT_STATUS = 'LINK_CA_CERT_STATUS',
  LINK_CA_CERT_ALGORITHM = 'LINK_CA_CERT_ALGORITHM',
  LINK_CA_CERT_AUDIT_TYPE = 'LINK_CA_CERT_AUDIT_TYPE',
  RULE_ALARM_CHANNEL_STATUS = 'RULE_ALARM_CHANNEL_STATUS',
  RULE_ALARM_CHANNEL_TYPE = 'RULE_ALARM_CHANNEL_TYPE',
  RULE_ALARM_STATUS = 'RULE_ALARM_STATUS',
  RULE_ALARM_LEVEL = 'RULE_ALARM_LEVEL',
  RULE_INSTANCE_TYPE = 'RULE_INSTANCE_TYPE',
  RULE_CONDITION_STATUS = 'RULE_CONDITION_STATUS',
  RULE_INSTANCE_STATUS = 'RULE_INSTANCE_STATUS',
  RULE_GROOVY_SCRIPT_CHANNEL_CODE = 'RULE_GROOVY_SCRIPT_CHANNEL_CODE',
  // ===== 北向集成 / 数据桥接 =====
  BRIDGE_DATA_SOURCE_TYPE = 'BRIDGE_DATA_SOURCE_TYPE',
  BRIDGE_DIRECTION = 'BRIDGE_DIRECTION',
  BRIDGE_MESSAGE_STATUS = 'BRIDGE_MESSAGE_STATUS',
  BRIDGE_HEALTH_STATUS = 'BRIDGE_HEALTH_STATUS',
  BRIDGE_TARGET_HANDLER = 'BRIDGE_TARGET_HANDLER',
  BRIDGE_SERIALIZATION = 'BRIDGE_SERIALIZATION',
  BRIDGE_TRIGGER_SOURCE = 'BRIDGE_TRIGGER_SOURCE',
  BRIDGE_PAYLOAD_KIND = 'BRIDGE_PAYLOAD_KIND',
  RULE_ALARM_RECORD_HANDLED_STATUE = 'RULE_ALARM_RECORD_HANDLED_STATUE',
  RULE_ALARM_SCENE = 'RULE_ALARM_SCENE',
  RULE_EVENT_TYPE = 'RULE_EVENT_TYPE',
  RULE_EFFECTIVE_TYPE = 'RULE_EFFECTIVE_TYPE',
  RULE_INSTANCE_ADDRESS = 'RULE_INSTANCE_ADDRESS',
  RULE_CONDITION_DEVICE_ACTION_TIRGGER_TYPE = 'RULE_CONDITION_DEVICE_ACTION_TIRGGER_TYPE',
  RULE_ALARM_TEMPLATE_VAR_ANCHORS = 'RULE_ALARM_TEMPLATE_VAR_ANCHORS',
  RULE_PLUGIN_INSTANCE_STATUS = 'RULE_PLUGIN_INSTANCE_STATUS',
  RULE_PLUGIN_INFO_STATUS = 'RULE_PLUGIN_INFO_STATUS',
  RULE_PLUGIN_INFO_LEVEL = 'RULE_PLUGIN_INFO_LEVEL',
  RULE_PLUGIN_INFO_TYPE = 'RULE_PLUGIN_INFO_TYPE',
  RULE_PLUGIN_INFO_RUN_MODE = 'RULE_PLUGIN_INFO_RUN_MODE',
  RULE_PLUGIN_INFO_LICENSE_TYPE = 'RULE_PLUGIN_INFO_LICENSE_TYPE',
  RULE_EXECUTION_LOG_STATUS = 'RULE_EXECUTION_LOG_STATUS',
  LINK_PRODUCT_TOPIC_TYPE = 'LINK_PRODUCT_TOPIC_TYPE',
  LINK_PRODUCT_TOPIC_FUNCTION_TYPE = 'LINK_PRODUCT_TOPIC_FUNCTION_TYPE',
  LINK_PRODUCT_TOPIC_PUBLISHER = 'LINK_PRODUCT_TOPIC_PUBLISHER',
  LINK_PRODUCT_TOPIC_SUBSCRIBER = 'LINK_PRODUCT_TOPIC_SUBSCRIBER',
  // OTA
  LINK_OTA_PACKAGES_TYPE = 'LINK_OTA_PACKAGES_TYPE',
  LINK_OTA_PACKAGES_STATUS = 'LINK_OTA_PACKAGES_STATUS',
  LINK_OTA_PACKAGES_SIGN_METHOD = 'LINK_OTA_PACKAGES_SIGN_METHOD',
  LINK_OTA_TASK_STATUS = 'LINK_OTA_TASK_STATUS',
  LINK_OTA_TASK_RECORD_STATUS = 'LINK_OTA_TASK_RECORD_STATUS',
  LINK_OTA_TASK_RECORD_APP_CONFIRM_STATUS = 'LINK_OTA_TASK_RECORD_APP_CONFIRM_STATUS', // ota升级任务 -- APP确认升级状态
  LINK_OTA_TASK_RECORD_COMMAND_SEND_STATUS = 'LINK_OTA_TASK_RECORD_COMMAND_SEND_STATUS', // ota升级任务 -- 指令下发状态
  LINK_OTA_UPGRADE_METHOD = 'LINK_OTA_UPGRADE_METHOD', // ota升级任务 -- 升级模式
  LINK_OTA_UPGRADE_SCOPE = 'LINK_OTA_UPGRADE_SCOPE', // ota升级任务 -- 升级范围
  // 设备分组
  LINK_DEVICE_GROUP_TYPE = 'LINK_DEVICE_GROUP_TYPE',
  // VIDEO
  VIDEO_APPLICATION_SCENARIO = 'VIDEO_APPLICATION_SCENARIO',
  VIDEO_MEDIA_SERVER_TYPE = 'VIDEO_MEDIA_SERVER_TYPE',
  VIDEO_MEDIA_STREAM_PROXY_TYPE = 'VIDEO_MEDIA_STREAM_PROXY_TYPE',
  VIDEO_MEDIA_STREAM_PROXY_RTP_TYPE = 'VIDEO_MEDIA_STREAM_PROXY_RTP_TYPE',
  VIDEO_MEDIA_STREAM_PROXY_STATUS = 'VIDEO_MEDIA_STREAM_PROXY_STATUS',
  VIDEO_DEVICE_TRANSPORT = 'VIDEO_DEVICE_TRANSPORT',
  VIDEO_DEVICE_STREAM_MODE = 'VIDEO_DEVICE_STREAM_MODE',
  VIDEO_DEVICE_ACCESS_PROTOCOL = 'VIDEO_DEVICE_ACCESS_PROTOCOL',
  VIDEO_DEVICE_SECRECY = 'VIDEO_DEVICE_SECRECY',
  VIDEO_GB28181_SIP_REGISTER_WAY = 'VIDEO_GB28181_SIP_REGISTER_WAY',
  VIDEO_MEDIA_ORIGIN_TYPE = 'VIDEO_MEDIA_ORIGIN_TYPE',
  VIDEO_DEVICE_CHANNEL_TYPE = 'VIDEO_DEVICE_CHANNEL_TYPE',
  VIDEO_DEVICE_STREAM_TYPE = 'VIDEO_DEVICE_STREAM_TYPE',
  VIDEO_DEVICE_CHANNEL_PTZ_TYPE = 'VIDEO_DEVICE_CHANNEL_PTZ_TYPE',
  VIDEO_DEVICE_ALARM_PRIORITY = 'VIDEO_DEVICE_ALARM_PRIORITY',
  VIDEO_DEVICE_ALARM_METHOD = 'VIDEO_DEVICE_ALARM_METHOD',
  VIDEO_DEVICE_ALARM_HANDLE_STATUS = 'VIDEO_DEVICE_ALARM_HANDLE_STATUS',
  NOTIFY_CHANNEL_TYPE = 'NOTIFY_CHANNEL_TYPE',
  NOTIFY_EVENT_TYPE = 'NOTIFY_EVENT_TYPE',
  VIDEO_PLATFORM_CASCADE_TYPE = 'VIDEO_PLATFORM_CASCADE_TYPE',
  VIDEO_PLATFORM_GB_VERSION = 'VIDEO_PLATFORM_GB_VERSION',
  VIDEO_PLATFORM_CATALOG_TYPE = 'VIDEO_PLATFORM_CATALOG_TYPE',
  VIDEO_GEO_COORD_SYS = 'VIDEO_GEO_COORD_SYS',
  VIDEO_RECORD_PLAN_TYPE = 'VIDEO_RECORD_PLAN_TYPE',
  VIDEO_RECORD_PLAN_STATUS = 'VIDEO_RECORD_PLAN_STATUS',
  VIDEO_RECORD_FILE_STATUS = 'VIDEO_RECORD_FILE_STATUS',
  VIDEO_RECORD_FILE_FORMAT = 'VIDEO_RECORD_FILE_FORMAT',
  VIDEO_DEVICE_GROUP_TYPE = 'VIDEO_DEVICE_GROUP_TYPE',
  VIDEO_DEVICE_POSITION_CAPABILITY = 'VIDEO_DEVICE_POSITION_CAPABILITY',
  // 渠道
  CARD_CHANNEL_OPERATOR = 'CARD_CHANNEL_OPERATOR', // 运营商
  CARD_CHANNEL_TYPE = 'CARD_CHANNEL_TYPE',
  CARD_CHANNEL_STATUS = 'CARD_CHANNEL_STATUS',
  CARD_CHANNEL_CONFIG_REQUEST_TYPE_CODE = 'CARD_CHANNEL_CONFIG_REQUEST_TYPE_CODE',
  CARD_CHANNEL_OFFICIAL_FLAG = 'CARD_CHANNEL_OFFICIAL_FLAG',
  // 卡片
  CARD_SIMINFO_CARD_TYPE = 'CARD_SIMINFO_CARD_TYPE',
  CARD_SIMINFO_SMSFLAG = 'CARD_SIMINFO_SMSFLAG',
  CARD_SIMINFO_GPRSFLAG = 'CARD_SIMINFO_GPRSFLAG',
  CARD_SIMINFO_CARRIER_TYPE = 'CARD_SIMINFO_CARRIER_TYPE',
  CARD_SIMINFO_STATUS = 'CARD_SIMINFO_STATUS',
  CARD_SIMINFO_USETYPE = 'CARD_SIMINFO_USETYPE',
  CARD_SIMINFO_ONLINE_FLAG = 'CARD_SIMINFO_ONLINE_FLAG',
  CARD_SIMINFO_STOP_CARD_TYPE = 'CARD_SIMINFO_STOP_CARD_TYPE',
  CARD_SIMINFO_LIMIT_STATUS = 'CARD_SIMINFO_LIMIT_STATUS',
  CARD_SIMINFO_SEARCHABLE_STATUS = 'CARD_SIMINFO_SEARCHABLE_STATUS',
  CARD_SIMINFO_LIMIT_FLAG = 'CARD_SIMINFO_LIMIT_FLAG',

  // CA 证书
  LINK_CA_LICENSE_STATUS = 'LINK_CA_LICENSE_STATUS',

  // enum
  ProjectTypeEnum = 'ProjectTypeEnum',
}

export enum MsgTemplateCodeEnum {
  // 注册短信
  REGISTER_SMS = 'REGISTER_SMS',
  // 注册邮件验证码
  REGISTER_EMAIL = 'REGISTER_EMAIL',
  //手机登录短信
  MOBILE_LOGIN = 'MOBILE_LOGIN',
  MOBILE_EDIT = 'MOBILE_EDIT',
  EMAIL_EDIT = 'EMAIL_EDIT',
}
