# spring配置
spring: 
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: thinglinks
    timeout: 30000
    jedis:
      pool:
      # 连接池中的最大空闲连接
        max-idle: 20
      # 连接池中的最小空闲连接
        min-idle: 0
      # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      # 开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
      seata: false
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/thinglinks?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: thinglinks
          password: NAhtGR8ByPpymakG
        # 从库数据源
        # slave:
          # username: 
          # password: 
          # url: 
          # driver-class-name: 

# rocketmq地址
rocketmq: 
  name-server: 127.0.0.1:19876
# 默认的消息组
  producer: 
    group: thinglinks-link

# xxl-job配置
thinglinks:
  link: 
    job:
      admin:
        addresses: http://127.0.0.1:18080/xxl-job-admin
      accessToken:
      executor:
        appname: thinglinks-link-job
        address: 127.0.0.1
        ip: 127.0.0.1
        port: 19905
        logpath: /www/server/thinglinks/xxljob/link
        logretentiondays: 30


threadBus:
  pool:
    core-pool-size: 1
    max-pool-size: 2
    keep-alive-time: 60
    queue-capacity: 200
    thread-name-prefix: thinglinksAsync-

# seata配置
seata:
  enabled: false
  # Seata 应用编号，默认为 ${spring.application.name}
  application-id: thinglinks-link
  # Seata 事务组编号，用于 TC 集群名
  tx-service-group: thinglinks-link-group
  # 关闭自动代理
  enable-auto-data-source-proxy: false
  # 服务配置项
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      thinglinks-link-group: default
  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace:
      
# mybatis配置
mybatis:   
  # 搜索指定包别名
  typeAliasesPackage: com.mqttsnet.thinglinks.link
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml

# swagger配置
swagger:
  title: Link模块接口文档
  license: Powered By thinglinks
  licenseUrl: https://showdoc.thinglinks.mqttsnet.com
