thinglinks:
  database:
    # 是否启用分布式事务. 为了大家上手简单默认关闭，但关闭后存在分布式事务不一致可能！！！生产一定设置为true，并启动seata
    # isSeata: true
    # initDatabasePrefix:
    #   - thinglinks_local_ds_c_base
  file:
    storageType: ALI_OSS  #  FAST_DFS LOCAL MIN_IO ALI_OSS HUAWEI_OSS QINIU_OSS
    delFile: false
    suffix: doc,docx,gif,jpeg,jpg,pdf,png,rar,zip,gzip,tar,gz,xz,xls,xlsx,txt,file,bin,dav,pack,deb,egp,egpx,apk,xml,rpx,rpg,html,htm,wps,xbid,db,jar,cer
    publicBucket: 
      - public
    local: 
      storagePath: /Users/mqttsnet/data/projects/uploadfile/file/     # 文件存储路径  （ 某些版本的 window 需要改成  D:\\data\\projects\\uploadfile\\file\\  ）
      urlPrefix: http://127.0.0.1/file/   # 文件访问 （部署nginx后，配置nginx的ip，并配置nginx静态代理storage-path地址的静态资源）
      innerUrlPrefix: null  #  内网的url前缀
    fastDfs:
      urlPrefix: https://fastdfs.mqttsnet.com/   
    ali:
      # 请填写自己的阿里云存储配置
      urlPrefix: "https://thinglinks.oss-cn-beijing.aliyuncs.com"
      bucket: "thinglinks"
      endpoint: "https://oss-cn-beijing.aliyuncs.com"
      accessKeyId: "your-aliyun-access-key-id"
      accessKeySecret: "your-aliyun-access-key-secret"
    minIo:
      endpoint: "https://minio.mqttsnet.com"
      accessKey: "your-minio-access-key"
      secretKey: "your-minio-secret-key"
      bucket: "thinglinks"
    huawei:
      urlPrefix: "https://huawei.mqttsnet.com/"
      endpoint: "obs.cn-southwest-2.myhuaweicloud.com"
      accessKey: "1"
      secretKey: "2"
      location: "cn-southwest-2"
      bucket: "pjcp-public"

    qiNiu:
      domain: qiniu.mqttsnet.com
      useHttps: true
      zone: "z0"
      accessKey: "1"
      secretKey: "2"
      bucket: "mqttsnet_admin_cloud"

#FAST_DFS配置
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 127.0.0.1:22122
  pool:
    #从池中借出的对象的最大数目
    max-total: 153
    max-wait-millis: 102
    jmx-name-base: 1
    jmx-name-prefix: 1


server:
  port: 18764

springdoc:
  group-configs:
    - group: 'base_common'
      displayName: '基础服务-公共模块'
      paths-to-match: '/**'
      packages-to-scan: com.mqttsnet.thinglinks.base.controller.common
    - group: 'base_user'
      paths-to-match: '/**'
      displayName: '基础服务-用户模块'
      packages-to-scan: com.mqttsnet.thinglinks.base.controller.user
    - group: 'base_system'
      paths-to-match: '/**'
      displayName: '基础服务-系统模块'
      packages-to-scan: com.mqttsnet.thinglinks.base.controller.system
    - group: 'base_file'
      paths-to-match: '/**'
      displayName: '基础服务-文件模块'
      packages-to-scan: com.mqttsnet.thinglinks.file.controller
    - group: 'base_msg'
      paths-to-match: '/**'
      displayName: '基础服务-消息模块'
      packages-to-scan: 
        - com.mqttsnet.thinglinks.msg.controller
        - com.mqttsnet.thinglinks.sms.controller
    - group: 'base_nacos'
      paths-to-match: '/**'
      displayName: '基础服务-Nacos模块'
      packages-to-scan: com.mqttsnet.thinglinks.nacos.controller
