server:
  port: 18762
  servlet:
    context-path: /${spring.application.name}   # 监控系统项目名

spring:
  security:
    user:
      name: thinglinks
      password: your-monitor-password
      roles: ACTUATOR_ADMIN

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    shutdown:
      access: unrestricted
    health:
      show-details: ALWAYS
