####### Mysql & Redis 配置 和 database.yml 、redis.yml 配置一样源的即可#######
mysql:
  host: 127.0.0.1:3306
  db: thinglinks_ds_c_defaults
  username: root
  password: your-mysql-password
  
# 默认激活环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}/${mysql.db}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${mysql.username}
    password: ${mysql.password}
  data:  
    redis:
      host: 127.0.0.1
      password: your-redis-password
      port: 6379
      database: 1
      timeout: 5000ms  # 操作超时时间
      connect-timeout: 3000ms  # 连接超时时间
      lettuce:
        pool:
          max-active: 1000  # 最大连接数，根据实际情况调整
          max-idle: 16    # 最大空闲连接数
          min-idle: 8     # 最小空闲连接数
          test-while-idle: true   # 空闲时检测连接
          test-on-borrow: true    # 借出时检测连接
          max-wait: 3000ms  # 获取连接的最大等待时间
          time-between-eviction-runs: 30000ms  # 空闲连接检测间隔
        shutdown-timeout: 100ms
        client:
          timeout: 30s

# 项目端口号
server:
  port: 18750

####### gateway config #######
gateway:
  path: /api
  rest: /rest
  manager:
    cache-type: local
    api: ${gateway.manager.cache-type}
    isv: ${gateway.manager.cache-type}
    secret: ${gateway.manager.cache-type}
    isv-api-perm: ${gateway.manager.cache-type}
  serialize:
    json-formatter: fastjson2
    date-format: yyyy-MM-dd HH:mm:ss

####### 参数名称定义 #######
api:
  app-id-name: app_id
  api-name: method
  format-name: format
  charset-name: charset
  sign-type-name: sign_type
  sign-name: sign
  timestamp-name: timestamp
  version-name: version
  notify-url-name: notify_url
  app-auth-token-name: app_auth_token
  biz-content-name: biz_content
  timeout-seconds: 300
  timestamp-pattern: yyyy-MM-dd HH:mm:ss
  zone-id: Asia/Shanghai

####### dubbo 配置 #######
dubbo:
  protocol:
    name: dubbo
    port: -1
    payload: 10485760
    parameters:
      sba: ignore    
  application:
    qos-enable: false
  registry:
    address: nacos://${thinglinks.nacos.username}:${thinglinks.nacos.password}@${thinglinks.nacos.ip}:${thinglinks.nacos.port}?namespace=${thinglinks.nacos.namespace}

####### file upload config #######
upload:
  one-file-max-size: 10MB
  total-file-max-size: 50MB


####### mybatis配置 #######
mybatis:
  fill:
    com.gitee.fastmybatis.core.support.LocalDateTimeFillInsert: created_time
    com.gitee.fastmybatis.core.support.LocalDateTimeFillUpdate: updated_time
  config-location: classpath:mybatis/mybatisConfig.xml
  print-sql: false

# log level
logging:
  level:
    com.gitee.sop: info
    com.gitee.sop.gateway.dao: error
    com.gitee.fastmybatis: info