server:
  port: 18767
  servlet:
    context-path: /thinglinks-job-admin

spring:
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    settings:
      number_format: 0.##########
      new_builtin_class_resolver: safer
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/thinglinks_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: your-mysql-password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    from: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

management:
  server:
    base-path: /actuator
  health:
    mail:
      enabled: false


# actuator 安全配置
actuator:
  security:
    username: actuator-admin
    password: your-actuator-password
    roles: ACTUATOR_ADMIN

mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

xxl:
  job:
    accessToken: abcd@1234@qwer
    i18n: zh_CN
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30