thinglinks:
  nacos:
    ip: ${NACOS_IP:@nacos.ip@}
    port: ${NACOS_PORT:@nacos.port@}
    namespace: ${NACOS_NAMESPACE:@nacos.namespace@}
    username: ${NACOS_USERNAME:@nacos.username@}
    password: ${NACOS_PASSWORD:@nacos.password@}
    group: DEFAULT_GROUP
    discovery:
      ip: ${NACOS_DISCOVERY_IP:@nacos.discovery.ip@}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: '@project.artifactId@'
  profiles:
    active: @profile.active@
  config:
    import:
      - nacos:common.yml?group=${thinglinks.nacos.group}&refresh=true
      - nacos:redis.yml?group=${thinglinks.nacos.group}&refresh=true
      - nacos:database.yml?group=${thinglinks.nacos.group}&refresh=true
      - nacos:${spring.application.name}.yml?refresh=true
  cloud:
    sentinel:
      enabled: true
      filter:
        enabled: true
      eager: true
      transport:
        dashboard: ${thinglinks.sentinel.dashboard}
    nacos:
      server-addr: ${thinglinks.nacos.ip}:${thinglinks.nacos.port}
      username: ${thinglinks.nacos.username}
      password: ${thinglinks.nacos.password}
      config:
        file-extension: yml
        namespace: ${thinglinks.nacos.namespace}
        enabled: true
      discovery:
        server-addr: ${thinglinks.nacos.ip}:${thinglinks.nacos.port}
        namespace: ${thinglinks.nacos.namespace}
        ip: ${thinglinks.nacos.discovery.ip}
        metadata: # 元数据，用于权限服务实时获取各个服务的所有接口
          management.context-path: ${server.servlet.context-path:}${spring.mvc.servlet.path:}${management.endpoints.web.base-path:}
          gray_version: mqttsnet
  boot:
    admin:
      discovery:
        ignored-instances-metadata:
          sba: ignore
          meta-v: 1.0.0
      instance-auth:
        default-user-name: ${ACTUATOR_USERNAME:${actuator.security.username:}}
        default-password: ${ACTUATOR_PASSWORD:${actuator.security.password:}}

# 用于/actuator/info
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
